FROM python:3
ADD requirements.txt /requirements.txt
ARG parser
RUN pip install -r /requirements.txt
ADD mindreader mindreader

ENV MQ_URL rabbitmq://127.0.0.1:5672
CMD ["python", "-m", "mindreader.parsers", "run-parser", ${PARSER}, ${MQ_URL}]