# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mindreader/drivers/encoders/mindreader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mindreader.drivers.reader.file_readers import cortex_pb2 as mindreader_dot_drivers_dot_reader_dot_file__readers_dot_cortex__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mindreader/drivers/encoders/mindreader.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n,mindreader/drivers/encoders/mindreader.proto\x1a\x33mindreader/drivers/reader/file_readers/cortex.proto\"P\n\tProtoUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\r\x12\x0e\n\x06gender\x18\x04 \x01(\t\"\xa2\x01\n\rProtoSnapshot\x12\x13\n\x04pose\x18\x01 \x01(\x0b\x32\x05.Pose\x12 \n\x0b\x63olor_image\x18\x02 \x01(\x0b\x32\x0b.ColorImage\x12 \n\x0b\x64\x65pth_image\x18\x03 \x01(\x0b\x32\x0b.DepthImage\x12\x1b\n\x08\x66\x65\x65lings\x18\x04 \x01(\x0b\x32\t.Feelings\x12\x1b\n\x08metadata\x18\x05 \x01(\x0b\x32\t.Metadata\"C\n\x08Metadata\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\r\x12\x13\n\x0bsnapshot_id\x18\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[mindreader_dot_drivers_dot_reader_dot_file__readers_dot_cortex__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTOUSER = _descriptor.Descriptor(
  name='ProtoUser',
  full_name='ProtoUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ProtoUser.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='ProtoUser.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='ProtoUser.birthday', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='ProtoUser.gender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=181,
)


_PROTOSNAPSHOT = _descriptor.Descriptor(
  name='ProtoSnapshot',
  full_name='ProtoSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='ProtoSnapshot.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color_image', full_name='ProtoSnapshot.color_image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='ProtoSnapshot.depth_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='ProtoSnapshot.feelings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='ProtoSnapshot.metadata', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=346,
)


_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Metadata.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Metadata.user_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='Metadata.snapshot_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=415,
)

_PROTOSNAPSHOT.fields_by_name['pose'].message_type = mindreader_dot_drivers_dot_reader_dot_file__readers_dot_cortex__pb2._POSE
_PROTOSNAPSHOT.fields_by_name['color_image'].message_type = mindreader_dot_drivers_dot_reader_dot_file__readers_dot_cortex__pb2._COLORIMAGE
_PROTOSNAPSHOT.fields_by_name['depth_image'].message_type = mindreader_dot_drivers_dot_reader_dot_file__readers_dot_cortex__pb2._DEPTHIMAGE
_PROTOSNAPSHOT.fields_by_name['feelings'].message_type = mindreader_dot_drivers_dot_reader_dot_file__readers_dot_cortex__pb2._FEELINGS
_PROTOSNAPSHOT.fields_by_name['metadata'].message_type = _METADATA
DESCRIPTOR.message_types_by_name['ProtoUser'] = _PROTOUSER
DESCRIPTOR.message_types_by_name['ProtoSnapshot'] = _PROTOSNAPSHOT
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA

ProtoUser = _reflection.GeneratedProtocolMessageType('ProtoUser', (_message.Message,), dict(
  DESCRIPTOR = _PROTOUSER,
  __module__ = 'mindreader.drivers.encoders.mindreader_pb2'
  # @@protoc_insertion_point(class_scope:ProtoUser)
  ))
_sym_db.RegisterMessage(ProtoUser)

ProtoSnapshot = _reflection.GeneratedProtocolMessageType('ProtoSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSNAPSHOT,
  __module__ = 'mindreader.drivers.encoders.mindreader_pb2'
  # @@protoc_insertion_point(class_scope:ProtoSnapshot)
  ))
_sym_db.RegisterMessage(ProtoSnapshot)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'mindreader.drivers.encoders.mindreader_pb2'
  # @@protoc_insertion_point(class_scope:Metadata)
  ))
_sym_db.RegisterMessage(Metadata)


# @@protoc_insertion_point(module_scope)
